# Generated by Django 4.1.7 on 2023-04-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0002_alter_usuario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('anodocarro', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
