# Generated by Django 4.1.7 on 2023-04-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carro', '0003_carrouso_alter_usuario_endereco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrouso',
            options={'verbose_name_plural': 'Seu Carro'},
        ),
    ]
